### ISSUE TITLE
XGBoostLSS Readme Review

### ISSUE THREAD

**Issue by StatMixedML** [StatMixedML/XGBoostLSS#2]
@uday1889: May I ask you to check out the readme and to provide a feedback.

**Comment by uday1889** [comment]
Hi Alex,

I see you've closed this one. Nut just wanted to say that you would like all the details with the code to go into a vignette rather than on the Readme. Just summarizing the main results on the Readme with a couple of plots should be fine.

I'll review it nevertheless for my learning. Great work! :)

Best,
Uday

**Comment by StatMixedML** [comment]
Hi Uday,

agree, all details should go into the vignette. But unless I have some more time to work on it + code, I`ll leave it in the readme for now.

Thanks,
Alex
